"""
run_training.py — Train the Color Wars neural network on MCTS self-play data.

This is the Phase 4 command-line entry point for training the dual-head
CNN on data generated by MCTS self-play.

Usage:
    cd ColorWars
    source .venv/bin/activate

    # Train on MCTS self-play data (default settings)
    python -m ai.scripts.run_training --data-dir data/mcts_self_play

    # Full training run with augmentation
    python -m ai.scripts.run_training \\
        --data-dir data/mcts_self_play \\
        --epochs 20 --batch-size 64 --lr 0.001 \\
        --augment

    # Resume from checkpoint
    python -m ai.scripts.run_training \\
        --data-dir data/mcts_self_play \\
        --resume ai/neural_net/checkpoints/colorwars_net_epoch010.pt \\
        --epochs 10

    # Train on random self-play data (for testing)
    python -m ai.scripts.run_training --data-dir data/self_play --no-policy-only

    # Quick test with model summary
    python -m ai.scripts.run_training \\
        --data-dir data/mcts_self_play \\
        --epochs 3 --max-games 10
"""

import sys
import os
import argparse

# Add project root to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from ai.neural_net.trainer import Trainer
from ai.neural_net.model import ColorWarsNet, get_device
from ai.neural_net import config


def main():
    parser = argparse.ArgumentParser(
        description="Train the Color Wars neural network.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  Default:    python -m ai.scripts.run_training --data-dir data/mcts_self_play
  Augmented:  python -m ai.scripts.run_training --data-dir data/mcts_self_play --augment
  Resume:     python -m ai.scripts.run_training --data-dir data/mcts_self_play --resume path/to/checkpoint.pt
        """,
    )

    # ── Data ──
    parser.add_argument(
        '--data-dir', type=str, required=True,
        help='Directory containing game JSON files'
    )
    parser.add_argument(
        '--max-games', type=int, default=None,
        help='Maximum number of games to load (None = all)'
    )
    parser.add_argument(
        '--augment', action='store_true',
        help='Apply 8-fold symmetry augmentation'
    )
    parser.add_argument(
        '--no-policy-only', action='store_true',
        help='Include examples without MCTS policy data'
    )

    # ── Training ──
    parser.add_argument(
        '--epochs', type=int, default=config.NUM_EPOCHS,
        help=f'Number of training epochs (default: {config.NUM_EPOCHS})'
    )
    parser.add_argument(
        '--batch-size', type=int, default=config.BATCH_SIZE,
        help=f'Batch size (default: {config.BATCH_SIZE})'
    )
    parser.add_argument(
        '--lr', type=float, default=config.LEARNING_RATE,
        help=f'Learning rate (default: {config.LEARNING_RATE})'
    )
    parser.add_argument(
        '--weight-decay', type=float, default=config.WEIGHT_DECAY,
        help=f'L2 regularization (default: {config.WEIGHT_DECAY})'
    )

    # ── Checkpoint ──
    parser.add_argument(
        '--checkpoint-dir', type=str, default=config.CHECKPOINT_DIR,
        help=f'Directory for checkpoints (default: {config.CHECKPOINT_DIR})'
    )
    parser.add_argument(
        '--resume', type=str, default=None,
        help='Resume training from a checkpoint file'
    )
    parser.add_argument(
        '--no-save', action='store_true',
        help='Do not save checkpoints'
    )

    args = parser.parse_args()

    # ── Banner ──
    device = get_device()
    print(f"\n{'═' * 60}")
    print(f"  COLOR WARS — NEURAL NETWORK TRAINING (Phase 4)")
    print(f"{'═' * 60}")
    print(f"  Data dir:        {args.data_dir}")
    print(f"  Max games:       {args.max_games or 'all'}")
    print(f"  Augmentation:    {'ON (8× symmetry)' if args.augment else 'OFF'}")
    print(f"  Policy only:     {'NO' if args.no_policy_only else 'YES'}")
    print(f"  Epochs:          {args.epochs}")
    print(f"  Batch size:      {args.batch_size}")
    print(f"  Learning rate:   {args.lr}")
    print(f"  Weight decay:    {args.weight_decay}")
    print(f"  Device:          {device}")
    if args.resume:
        print(f"  Resuming from:   {args.resume}")
    print(f"{'═' * 60}\n")

    # ── Create or load model ──
    if args.resume:
        trainer = Trainer(
            device=device, lr=args.lr,
            weight_decay=args.weight_decay,
            batch_size=args.batch_size,
        )
        trainer.load_checkpoint(args.resume)
    else:
        model = ColorWarsNet()
        model.summary()
        trainer = Trainer(
            model=model, device=device, lr=args.lr,
            weight_decay=args.weight_decay,
            batch_size=args.batch_size,
        )

    # ── Load data ──
    n_train, n_val = trainer.load_data(
        data_dir=args.data_dir,
        augment=args.augment,
        policy_only=not args.no_policy_only,
        max_games=args.max_games,
    )

    if n_train == 0:
        print("  ❌ No training examples found. Exiting.")
        return 1

    # ── Train ──
    metrics = trainer.train(n_epochs=args.epochs)

    # ── Save checkpoint ──
    if not args.no_save:
        config.CHECKPOINT_DIR = args.checkpoint_dir
        filepath = trainer.save_checkpoint()

    # ── Summary ──
    first = metrics[0]['train']
    last = metrics[-1]['train']
    print(f"\n{'─' * 55}")
    print(f"  TRAINING SUMMARY")
    print(f"{'─' * 55}")
    print(f"  Total epochs:     {len(metrics)}")
    print(f"  Loss:  {first['total_loss']:.4f} → {last['total_loss']:.4f}")
    print(f"  Policy accuracy:  {first['policy_accuracy']:.1f}% → "
          f"{last['policy_accuracy']:.1f}%")
    if metrics[-1]['val']:
        val_last = metrics[-1]['val']
        print(f"  Val loss:         {val_last['total_loss']:.4f}")
        print(f"  Val accuracy:     {val_last['policy_accuracy']:.1f}%")
    print(f"{'═' * 55}\n")

    return 0


if __name__ == '__main__':
    sys.exit(main())
